### ISSUE TITLE
The mod cannot be run on the server side.

### ISSUE THREAD

**Issue by oOBoomberOo** [U1timateJ7/CustomBlocks#10]
**Describe the bug**
The mod crashed on startup when using it on the server-side.
attached log: [latest.log](https://github.com/U1timateJ7/CustomBlocks/files/7860358/latest.log)

**To Reproduce**
1. Download and extract this [reproduce.zip](https://github.com/U1timateJ7/CustomBlocks/files/7860351/reproduce.zip) environment.
2. Start the server with `java -jar fabric-server.jar nogui` command.
3. Wait for the server to crash.

**Versions:**
mod: `1.5.0-1.18.1`
fabric: `0.12.12`
minecraft: `1.18.1`
java: `17.0.1`

**Comment by U1timateJ7** [comment]
I will have to look into this

**Comment by U1timateJ7** [comment]
Thanks for bringing this bug to my attention. I will start testing on the server side.

**Comment by Happyperson3796** [comment]
This bug is still active in the latest forge version of the mod. Is there any fix?
