### ISSUE TITLE
Rotation types y_axis_player and all_player do not work differently than their counterparts

### ISSUE THREAD

**Issue by KMorris29** [U1timateJ7/CustomBlocks#11]
**Describe the bug**
The rotation types all and y_axis work like with most directional blocks in MC, where the facing: direction is towards the player's facing: direction as seen in f3 mode.
The problem is that giving a block y_axis_player or all_player does not change this behavior, locking the block-maker out of using "observer-style" rotations.

**To Reproduce**
Make a block with rotation_type all. Place it down in any direction, then place a piston right next to it. You will see that the block and piston have the same facing direction. Now place down an observer. The observer is facing away from where the player is at, towards where the player is looking.
Now change the block to rotation_type all_player in the json file, and restart the MC instance.
The block's placing behavior does not change, even though it should work like an observer now.
Similar behavior is found with rotation_type y_axis_player vs y_axis.

**Expected behavior**
I was attempting to create some blocks that work similar to magenta glazed terracotta: when placed on the ground in front of you, an arrow on top points in the direction you are looking in. As best I can tell, this is impossible without either messing around with events and commands to rotate the block, or rotating all of my textures to be upside down. Note that the arrow in magenta glazed terracotta's texture within MC's files is pointed towards the top.

**Mod Versions:**
 - Mod Version 1.5.0
 - MC Version 1.18.1

**Comment by KMorris29** [comment]
Oh yeah I meant to mention: changing a block's rotation_type within the json file, as long as you restart the entire game, does work to change how the block rotates between axis, y_axis, and all. It's only if going from y_axis to y_axis_player, or all to all_player, that nothing happens.

**Comment by U1timateJ7** [comment]
I am not finding this issue
