### ISSUE TITLE
Custom block models, and custom rotation

### ISSUE THREAD

**Issue by DuendeInexistente** [U1timateJ7/CustomBlocks#13]
Custom block models would be good to have. If possible, allow them to be larger than a block (I don't know if this is an issue codewise, just pointing it out) so one can have a block that say looks like an animal.
Additionally, some way to rotate these blocks to a full 360º degrees. Maybe a right click menu that one can enable when creating the object.

**Comment by U1timateJ7** [comment]
Custom block models have been implemented as an experimental feature of blocks for a while now and blocks have the ability to rotate 360 degrees base on how you place it and its file.
