### ISSUE TITLE
Custom Item Models are Stored in the Blocks folder.

### ISSUE THREAD

**Issue by LucasLDZ** [U1timateJ7/CustomBlocks#15]
When trying to add custom models, adding blocks makes sense. You add the models to the folder **custom_blocks/blocks/models**.

But when adding custom item models, you have to add them to  **custom_blocks/blocks/item_models**, which just doesn't make sense.

Also these folders do not generate on their own. It would be nice to have these auto generate.

**Comment by U1timateJ7** [comment]
I must have been very tired while implementing that feature. I will fix it as soon as I can.

**Comment by U1timateJ7** [comment]
What version of minecraft were you playing with

**Comment by U1timateJ7** [comment]
The directory items/models does exist for items that do not have a block associated with them. For block item models, blocks/item_models exists.
