### ISSUE TITLE
Custom Blocks Crashes in Fabric

### ISSUE THREAD

**Issue by KirbyKid256** [U1timateJ7/CustomBlocks#3]
Hi, so I've been having a problem getting Minecraft to load with this mod in Fabric as the loading process crashes each time I use the mod. All I have in my mods folder are Fabric API and the Custom Blocks mod. Here's my crash report of when I tried to use the mod.
[crash-2021-09-02_08.49.33-client.txt](https://github.com/U1timateJ7/CustomBlocks/files/7099018/crash-2021-09-02_08.49.33-client.txt)

 - Mod Version 1.3.0
 - MC Version 1.17.1

**Comment by U1timateJ7** [comment]
The painting JSON you used must not be a valid JSON file. Make sure the files used are valid. A useful website to validate JSON files is https://jsonlint.com. I will make it so instead of crashing, it doesn't load the Custom element
