### ISSUE TITLE
Future Features

### ISSUE THREAD

**Issue by lubcubsgaming** [U1timateJ7/CustomBlocks#4]
Feature Requests 

1: The ability to select drops from a gui, and also allow drops to be a loot table, so you can have random assortments of items and counts.

2: When recipes are implemented, it would be cool if the recipes were done in a gui, you select each item that you want to be able to add into the recipe, and you select the output item.

3: Ability to add NBT data to the files. Would be cool if we can make blocks drop various vanilla items, with different names, custom model datas, tags, etc.

4: More item types. Would be fun to be able to make armor, specific tools, guns that when right clicked, shoot an item that you set up and projectiles that can be thrown like snow balls. It would also be a cool feature to be able to execute a command when those projectile types hit the ground.

5: Executing/effects. Maybe the ability to give a potion effect when holding or wearing. A right click effect that would execute a command or multiple effects when you right clicked. 

6: Pack locations. Instead of the packs being created in the config files, it might be better for sharing, if when a pack was created, it was created as an addon instead. And each item, or block, or recipe or whatever, gets its own folder within the pack, instead of everything going inside the pack file.

These are just some suggestions from a mod called "additions" that I think might be dead. It was 1.12.2 and we are now 1.17/1.18 lol. These features and many others, were widely used and I think if they are possible to add, could make this one of the only mods people need to create a bunch of new addon packs. Either way, love the mod! And can't wait to see everything that comes out of it!

Also I know some of these might already be planned since some of them are experimental features right now :)

**Comment by U1timateJ7** [comment]
Added the loot table option for block drops. If the drops parameter is a string, it will instead grab from the loot table corresponding to the identifier.

ex: "drops": "minecraft:chests/bastion_treasure"

**Comment by U1timateJ7** [comment]
Working on 5 at the moment

**Comment by lubcubsgaming** [comment]
that's awesome!

**Comment by lubcubsgaming** [comment]
Another suggestion! Custom Lore with the option to add 1, 2 or 3 lines of lore with different colors!
