### ISSUE TITLE
Texture Button.

### ISSUE THREAD

**Issue by NotoriousLemon** [U1timateJ7/CustomBlocks#7]
On the block maker screen, pressing the textures folder button does not open a folder.
I am also not clear on how to apply textures to a block after reading the wiki, but that is more than likely not a bug and i am just stupid.

**Mod Versions:**
 - Mod Version [e.g. 1.5.0.1]
 - MC Version [e.g. 1.18]

**Comment by U1timateJ7** [comment]
Did you have the namespace field or texture namespace field filled out?

**Comment by NotoriousLemon** [comment]
Both, yes. Though i may be placing the texture in the wrong spot. Its something like this .minecraft\config\custom_blocks\custom_blocks_resources\assets\dg\textures\block, with dg being the name space. I just put the 160x160 texture in the block folder.

**Comment by U1timateJ7** [comment]
Is the texture namespace also dg?
