### ISSUE TITLE
A sort of preset menu for creating blocks

### ISSUE THREAD

**Issue by Infant-Anihilator** [U1timateJ7/CustomBlocks#8]
i think that it would be cool to have like a sort of drop-down menu where you can have all sorts of presets nfor blocks. For ezmple, if you pick stone from the list, it will automatically fill out all of the values with the default values that most stone type blocks have.

something else that would be neat is the ability to copy values if you tweaked them and put them into the preset menu, but i'd be more than happy to have just the preset menu, as that would make it easier to create blocks in bulk.

**Comment by U1timateJ7** [comment]
That's a very neat idea

**Comment by U1timateJ7** [comment]
I'll definitely try adding this

**Comment by U1timateJ7** [comment]
Added in 1.6.0
