### ISSUE TITLE
custom block gui issue

### ISSUE THREAD

**Issue by Gabboo2** [U1timateJ7/CustomBlocks#9]
maybe I'm just really really dumb or really really blind..I can't seem to find the in game gui thing ^_^' is there a certain library mod or core mod I need?

**Comment by U1timateJ7** [comment]
If you are using the forge version, it does not exist yet.

**Comment by U1timateJ7** [comment]
If you are using the fabric version, it's a button on the main menu or pressing **B** in a world

**Comment by Gabboo2** [comment]
OHHH ok! Thanks!
